<?php
include 'connection/connect.php';
session_start();
error_reporting(0);


?>



<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">

 <?php include 'pages/head.php';?>
 <style type="text/css">
    .show-read-more .more-text{
        display: none;
    }
</style>


  <div id="focus-overlay"></div>
  <body id="body">
    <a href="#body" id="back-to-top"><i class="zmdi zmdi-chevron-up"></i></a>
              
          <?php include 'pages/header.php';?>  
          <?php include 'pages/m_header.php';?>   
            
                <section class="dark under-head-cont" id="infinity-breadcrumb">
            	<div class="container">
            		<h2>REMOVE MY DATA</h2>
            		
            	</div>
            </section>
            
            <section class="breadcrumb-section">
            	<div class="container content">
            		<div class="row main-content">
            			<div class="col-md-8">				
            				<div class="panel panel-body panel-default">
            					<h3>Consequences of My Actions</h3>
                        <p>
                             If you accidentally clicked on a short URL, or viewed a webpage with invisible image logger generated by someone using this website without your prior acknowledgment and consent we recommend you to immediately remove the information that could potentially be recorded in our database regarding your click or view. Although none of your personal identifiable information can be collected with ahref.tech URLs and IP-loggers, this measure will help you to minimize the risk of making your personal information available to someone else.</p>
                          <p>
                            You can remove the record with your information from the database by providing the short URL that you clicked. In order to identify and delete your information from our database we have to detect your current IP address and information about your device. The detected information will not be saved in our database. If you decide to proceed you provide your full consent for us to detect your IP address and device information for the purpose of removal from the database.</p>


                            <p>
                              Please note that if your IP address or device information has changed, it may not be possible to identify your record in the database and remove it as it doesn’t have any information that can identify you.
                            
                            
                        </p>
            
            
            
            				</div>
            				
            			
            				
            					
            			</div>
            			<div class="col-md-4">
            								<div class="panel panel-default panel-body" id="widget_social_count"><h3>We are social</h3><p><em></em> Facebook Likes</p><a href='#' target='blank' class='btn-block btn btn-facebook'>Like us on Facebook</a><a href='#' target='blank' class='btn-block btn btn-twitter'>Follow us on Twitter</a></div>		
            								</div>
            		</div>		
            	</div>
            </section>    
            
            
           <section class="breadcrumb-section" style="margin-top:5px;">
            	<div class="container content">
            		<div class="row main-content">
            			<div class="col-md-12">				
            				<div class="panel panel-body panel-default">
            				    
            				 
            				
            				
            			
                            <h3>Please note that if your IP address or device information has changed, it may not be possible to identify your record in the database and remove it as it doesn’t have any information that can identify you. </h3>
                            
                            <form method="post">
                                
                                
                                
                                
                                 <?php

                	 $urlinput=mysqli_real_escape_string($con,htmlentities($_POST['linkremoval'])); //getting the code only
                	 $urlinput = strpos($urlinput, 'http') !== 0  || strpos($urlinput, 'https') !== 0 ? "http://$urlinput" : $urlinput;
                	 
                	 
                     $base_url_code = basename($urlinput);  // getting the code only
                
                	 
                
                   
                   

                	if(isset($_POST['remove']))
                	{
                	    
                            $responseKey = mysqli_real_escape_string($con,htmlentities($_POST['g-recaptcha-response'])); //responce_key_callback_by_google
                            $ipaddress = $_SERVER['REMOTE_ADDR']; //user_ip_address
                           $google_api_url = "https://www.google.com/recaptcha/api/siteverify?secret=$secretKey&response=$responseKey&remoteip=$ipaddress"; // google_api_url
                            $response = file_get_contents($google_api_url);
                            $response = json_decode($response);
                           
                	 
                     	if(empty( $_POST['linkremoval']) ||  $_POST['linkremoval']=='')
                		{
                		      	echo '
                                    
                                      <div class="container py-5">  
                                       
                                        <div class="alert alert-danger">  
                                            <button type="button" class="close" data-dismiss="alert">×</button>  
                                            <strong>Opps!</strong> link was not entered, please try again below: 
                                        </div>  
     
        
                                    </div>   ';
                		}
                
                	   elseif($response->success == false)
                        {
                            	echo '
                                 <div class="container py-5">  
                                       
                                        <div class="alert alert-danger">  
                                            <button type="button" class="close" data-dismiss="alert">×</button>  
                                            <strong>Opps!</strong> You Missed the Captcha, please try again below: 
                                        </div>  
     
        
                                    </div>  ';
                                
                                
                        }
                  
                     else if(strlen($base_url_code) < 6 || strlen($base_url_code) > 6)  //$base_url_code  length
                                	{
                        	
                        	
                        		         
                                        
                        		echo  '    <div class="alert alert-danger">  
                                                                <button type="button" class="close" data-dismiss="alert">×</button>  
                                                                                    <strong>invalid!</strong> Url length. 
                                                                                </div>  ';	 
                                            
                                   
                        }
                       
                   else{
                           
                                
                		   $sql = "select ip from tracking_data where ip='".$ipaddress."' ";
                		   $rec = mysqli_query($con,$sql);
                		   $exist = mysqli_num_rows($rec);
                		   
                		   
                            		 if($rec)
                            		 {
                            		        
                            		         if($exist > 0)
                                              {
                            	                      $sql_del = "delete from tracking_data where ip='".$ipaddress."' ";
                		                              $rec_del = mysqli_query($con,$sql_del);
                		                              
                		                          	 if($rec_del)
                            		                  {    
                                        	                echo '
                                                            
                                                                   
                                                                    <div class="alert alert-success">  
                                                                        <button type="button" class="close" data-dismiss="alert">×</button>  
                                                                        <strong>Your All records deleted successfully.</strong>  
                                                                    </div>  
                                 
                                    
                                                               ';
                                                          } 
                                                          else
                                    		                    {
                                    		     
                                                    
                                                                        echo '
                                                                                
                                                                                       
                                                                                        <div class="alert alert-warning">  
                                                                                            <button type="button" class="close" data-dismiss="alert">×</button>  
                                                                                            <strong>There is No data is found in our databse!</strong>  
                                                                                        </div>  
                                                     
                                                        
                                                                                   ';
                                                    
                                                    
                                    		                     }
                                                 
                                            }
                                            else
                                    		 {
                                    		     
                                                    
                                                    echo '
                                                            
                                                                   
                                                                    <div class="alert alert-warning">  
                                                                        <button type="button" class="close" data-dismiss="alert">×</button>  
                                                                        <strong>There is No data is found in our databse!</strong>  
                                                                    </div>  
                                 
                                    
                                                               ';
                                                    
                                                    
                                    		 }
                            		         
                            		         
                                        	
                            		     
                            		     
                            		 }
                            		 else
                            		 {
                            		     
                                            
                                            echo '
                                                     <div class="container py-5">  
                                                           
                                                            <div class="alert alert-danger">  
                                                                <button type="button" class="close" data-dismiss="alert">×</button>  
                                                                <strong>Critical Alert!</strong>  Something happen with Query! Contact developer support!:( 
                                                            </div>  
                         
                            
                                                        </div>  ';
                                            
                                            
                            		 }
                              
                                
                                
                                
                        }
                	
                	}
                	
                
                
                	
                	?>
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                   
                                
                              <div class="form-group">
                                <label for="link">Link:</label>
                                <input type="text" class="form-control" id="link"  name="linkremoval" placeholder="http://domain.com/url/xxxxxx">
                           
                              </div>
                              
                               <div class="form-group">
                               
                                <div  class="g-recaptcha" data-sitekey="<?php echo $siteKey; ?>"></div>
                           
                              </div>
                            
               
                             
                             
                              <button type="submit" name="remove" class="btn btn-primary">Remove</button>
                            </form>
                      
            
            
                             
            
            
            
            				</div>
            				
            					
            			</div>
            		
            		</div>		
            	</div>
            </section>    
            
            
            
            
            
            
            
            

 <?php include 'pages/footer.php';?>  
     
      
  <?php include 'pages/jquery.php';?>  
	  
  <script src='https://www.google.com/recaptcha/api.js'></script>


	</body>


</html>
